### ISSUE TITLE
DistNet errors

### ISSUE THREAD

**Issue by MoMa941** [jeanollion/bacmman#14]
Dear @jeannollion,

I am currently trying to use DistNet for segmentation and tracking, but for some reason I only get errors. Even when I use the example dataset and images, no bacteria are segmented. A couple weeks ago I was still able to use DistNet, so I was wondering if anything changed in the meantime, or if my ImageJ is the problem. 

Kind regards,

Tom

**Comment by jeanollion** [comment]
Dear Tom, 
Nothing has changed with DiSTNet (1d version as opposed to the new DiSTNet2D) in the last months. I just tested on the sample dataset and I don't have errors. 
Could you provide more information: about your OS & hardware (CPU architecture, GPU.. ) if they have changed  and the stack trace of the error. 
Regarding the CPU architecture, the new mac CPU (ARM) are not supported yet by the java bindings of tensorflow. 
Best, 
Jean

**Comment by MoMa941** [comment]
Where previously no image opened when trying to segment bacteria, now the image opens but no bacteria are segmented. I am using Windows 11 with an Intel Core i7 CPU. Nothing changed in this since last time. The error I am getting is: 


[ERROR] Errors for Task: db:dataset1_DL; structures:[1]; positions:[0]; segmentAndTrack; dir:C:\Users\tomde\Data_MEP_DL\dataset1_DL
[ERROR] P:0/S:0/I:0-6;P:0/S:0/I:0-8;P:0/S:0/I:0-2;P:0/S:0/I:0-0;P:0/S:0/I:0-7;P:0/S:0/I:0-5;P:0/S:0/I:0-3;P:0/S:0/I:0-4;P:0/S:0/I:0-1
java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.proto.framework.ConfigProto$DeviceCountDefaultEntryHolder
	at org.tensorflow.proto.framework.ConfigProto$Builder.internalGetDeviceCount(ConfigProto.java:4616)
	at org.tensorflow.proto.framework.ConfigProto$Builder.buildPartial(ConfigProto.java:4403)
	at org.tensorflow.proto.framework.ConfigProto$Builder.build(ConfigProto.java:4392)
	at bacmman.plugins.plugins.dl_engines.TF2engine.init(TF2engine.java:70)
	at bacmman.plugins.plugins.trackers.DistNet.predict(DistNet.java:56)
	at bacmman.plugins.plugins.trackers.DistNet.segmentAndTrack(DistNet.java:47)
	at bacmman.plugins.plugins.processing_pipeline.SegmentAndTrack.segmentAndTrack(SegmentAndTrack.java:68)
	at bacmman.data_structure.Processor.execute(Processor.java:423)
	at bacmman.data_structure.Processor.lambda$executeProcessingScheme$8(Processor.java:326)
	at bacmman.utils.ThreadRunner.lambda$executeAndThrowErrors$3(ThreadRunner.java:271)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1652)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at bacmman.utils.ThreadRunner.executeAndThrowErrors(ThreadRunner.java:269)
	at bacmman.data_structure.Processor.executeProcessingScheme(Processor.java:325)
	at bacmman.core.Task.process(Task.java:901)
	at bacmman.core.Task.runTask(Task.java:789)
	at bacmman.core.Task.lambda$executeTasks$30(Task.java:1237)
	at bacmman.core.DefaultWorker.doInBackground(DefaultWorker.java:96)
	at bacmman.core.DefaultWorker.doInBackground(DefaultWorker.java:34)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by jeanollion** [comment]
The error comes from the tensorflow java binding, it seems a dependency is not found. 
Check that the following jars are present in your Fiji directory (they are installed along with BACMMAN-DL update site): 
- jars/tensorflow-core-api-0.4.1.jar
- jars/win64/tensorflow-core-api-0.4.1-windows-x86_64.jar
- lib/win64/vcruntime140_1.dll

It is strange however that it suddenly stops working. 
Jean

**Comment by MoMa941** [comment]
That is strange. All these jars are present in my FIJI directory. I do notice that there are also two other tensorflow jars in the directory (jars/tensorflow-1.12.0 and jars/imagej-tensorflow-1.1.6), could these possibly be causing any problems?

Best,

Tom

**Comment by jeanollion** [comment]
yes possibly. if removing them do not work, try a fresh install. 
Best, 
Jean

**Comment by jeanollion** [comment]
Hi Tom, 
Is your problem solved ? 
Jean

**Comment by jeanollion** [comment]
tensorflow 1x jars may be there because you installed other plugins that depend on tensoflow 1x. To avoid this it is safer to have a dedicated Fiji install for bacmman
